version: build{build}

branches:
  except:
    - project/travis

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set GOPATH=c:\gopath
  - set QTDIR=C:\Qt\5.9.7\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;%GOPATH%\bin;
  - set ROOT_DIR=%cd%
  - go get qpm.io/qpm
  - go install qpm.io/qpm
  - dir %GOPATH%\bin

  - cd %ROOT_DIR%
  - cd source\Flux-Application-Full && qmake && nmake
  
  - cd %ROOT_DIR%
  - cd source/Qt-Qml-Library-Project && qmake && nmake
 
